### ISSUE TITLE
Automatically sync dependencies to app `package.json`

### ISSUE THREAD

**Issue by jaysoo** [nrwl/nx-react-native#12]
## What?

We want autolink to work, which means.

1. When running `run-ios` or `run-android`, we want the app's `package.json` to be updated with npm dependencies used by the app.
2. A builder to sync dependencies to `package.json` (in case users want to run `pod install` manually for example). This should be run as `nx sync-deps [app]`.

## Why?

React native require dependencies to be in the app's `package.json` file in order to autolink native modules. Just having the packages listed in the workspace `package.json` is not enough.

For example, if you used `react-native-image-picker` in your app (or a lib used by the app), then you will need this entry in the app `package.json`:

```
{
  "react-native-image-picker": "*"
}
```

The version `*` doesn't do anything since we don't use it to install anything, just to link.

## How?

We can read in the dep graph and look for any `type: npm` dependencies. Note, we also need to walk the libs used by the app and pick up any native modules used by them.

**Comment by trumbitta** [comment]
Is there in this something that "normal" publishable libs could also benefit from?

**Comment by jaysoo** [comment]
@trumbitta We do pick up workspace dependencies when using buildable and publishable libs. So if you run `nx build  ... --withDeps` it'll build the dependencies in topological order. Is that what you mean?

**Comment by trumbitta** [comment]
@jaysoo I mean automagically adding deps to the `package.json` of a publishable lib when preparing the npm package :D
