### ISSUE TITLE
npx nx g @nrwl/react-native:app throws error

### ISSUE THREAD

**Issue by alveshelio** [nrwl/nx-react-native#16]
I'm working on a project set up with `nx` and I have a web app in next and I want to create a mobile app. When I run this command `npx nx g @nrwl/react-native:app mobile-app` it throws this error: **ignore_1.default is not a function**

I have nx 10.4.4.

**Comment by jaysoo** [comment]
@alveshelio Which version of `@nrwl/react-native` are you using? Can you try the latest `10.4.2`?

**Comment by alveshelio** [comment]
Hi @jaysoo,

I've installed @nrwl/react-native 10.4.4 and it fixed the issue.

Thank you very much for your help.
