### ISSUE TITLE
Migration Issues

### ISSUE THREAD

**Issue by ceremonious** [nrwl/nx-react-native#18]
I'm excited to see the release of nx-react-native. We started working on a new React Native project recently, and I spent this afternoon migrating it to NX. I followed this [migration guide](https://blog.nrwl.io/introducing-react-native-support-for-nx-48d335e90c89) and ran into a couple of issues, so I wanted to document them here in case others ran into the same issues. Our project was a base React Native project with some native modules (no Expo). Most of our config was unchanged from the default React Native setup. We're only deploying to iOS right now, so I can't speak to any issues that might pop up with Android.

1) Our auto-generated Podfile had relative imports at the top that looks like this:  `require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'`, so I had to change them to look like this: `require_relative '../../../node_modules/@react-native-community/cli-platform-ios/native_modules'`

2) Our Podfile had the line: `use_react_native!(:path => config["reactNativePath"])`, which I needed to change to `use_react_native!(:path => config[:reactNativePath])`

3) I needed to update our `tsconfig.json` file to extend our base tsconfig

4) After making the above fixes, I was able to run our app locally & on a simulator. However, I was running into issues when trying to deploy to TestFlight via Fastlane. When I looked at the logs, I saw that XCode was looking for `index.js` in our base repo folder, instead of in `apps/my-native-app/`. In the Build Phases tab in XCode, we had the following script under "Bundle React Native code and images":

```
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh
```

I fixed the build by updating this to:
```
export NODE_BINARY=node
export ENTRY_FILE=./apps/my-native-app/index.js
../../../node_modules/react-native/scripts/react-native-xcode.sh
```

Hopefully this helps anyone else migrating! 

Additionally, right now I'm running Fastlane from the /ios folder. Are there any plans to integrate Fastlane into nx-react-native? Not sure if that falls under NX's scope.

**Comment by jaysoo** [comment]
Hey @ceremonious thanks for the info!

We will be migrating the react-native plugin back into the main repo soon, and we'll also be providing extra guides on nx.dev in the next couple of months.

For now, I will update the blog post to reflect some of the issues you found.

**Comment by jaysoo** [comment]
For `10.4.7` (currently in beta), many of the migration steps will be removed.

In order for `pnpm` to work, we need to symlink all of the required node  modules for the build scripts anyway, so the normal relative paths from React Native will work! :)

**Comment by jaysoo** [comment]
Closing this issue since the migration instructions are updated on blog post.
