### ISSUE TITLE
NX Library Import not working with 0.63.3

### ISSUE THREAD

**Issue by ceremonious** [nrwl/nx-react-native#24]
I upgraded our React Native version from 0.63.2 to 0.63.3 and I'm getting the following issue when trying to build the release iOS version via Fastlane:

```
error Unable to resolve module `@heartbeat/heartbeat-frontend-data` from `apps/heartbeat-react-native/src/data/store.ts`: @heartbeat/heartbeat-frontend-data could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*. Run CLI with --verbose flag for more details
```

`heartbeat-frontend-data` is a NX library in the same workspace that I'm trying to import. Everything works fine when using React Native 0.63.2

**Comment by jaysoo** [comment]
@ceremonious What does your `tsconfig.base.json` look like at the workspace root? Does it have the mappings in paths section?

**Comment by ceremonious** [comment]
Yea, our `tsconfig.base.json` has the mappings in the paths section.

`
"paths": {
      ...,
      "@heartbeat/heartbeat-frontend-data": [
        "libs/heartbeat-frontend-data/src/index.ts"
      ]
    },
`

**Comment by jaysoo** [comment]
And do you see the same problem with react-native `0.63.4`? I'm trying to reproduce the problem but cannot. Is your repo public by any chance?

**Comment by ceremonious** [comment]
Yea, we're running into the same issue with `0.63.4`. Unfortunately, our repo is not public. Do you have a public repo available using nx-react-native? Our babel/metro settings might be configured differently. 

I tried creating a fresh NX workspace to set up a fresh nx-react-native setup, but I'm running into the following error after running `npx create-nx-workspace`: 

_No valid exports main found for '/private/var/folders/cb/wg4h2myj7gq1qz9rw3gmtj200000gn/T/tmp-`555730KqUeS19OOzA/node_modules/yargs-parser_

I'm guessing this error is a separate issue.

**Comment by jaysoo** [comment]
Are you able to share your metro config?

**Comment by ceremonious** [comment]
We're using the metro config that NX generates (I copied it over when I did the migration):  

```
const { withNxMetro } = require('@nrwl/react-native');

module.exports = withNxMetro({
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
});
```

**Comment by jaysoo** [comment]
What about the `babel.config.js` file? Any changes there?

**Comment by ceremonious** [comment]
That might be the issue, the `babel.config.js` inside `apps/heartbeat-react-native` is (which was copied over):

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
};
```

However, the `babel.config.js` in our base workspace folder is:

```
{
  "presets": ["@nrwl/web/babel"],
  "babelrcRoots": ["*"]
}
```

Should `module:metro-react-native-babel-preset` be in the base `babel.config.js`?

**Comment by jaysoo** [comment]
> Should module:metro-react-native-babel-preset be in the base babel.config.json?

No, the  root babel config shouldn't be used by React Native because it probably doesn't look "upward" from the app root.

I've created a workspace here that has a React Native app with workspace libs. https://github.com/jaysoo/acme

```
nx run-ios mobile
```

Does that compile and run for you? Note that when you add a new workspace lib, you will need to restart the packager to pick up new paths (I'm looking at an enhancement for this).

**Comment by ceremonious** [comment]
I'm getting the same issue with the example repo:

```
error Unable to resolve module `@acme/ui-header` from `apps/mobile/App.tsx`: @acme/ui-header could not be found within the project.
```

To clarify, I'm getting this error when I build using Fastlane in order to deploy to Testflight, not during development. However, I also got the same error when doing a release build via XCode. 

To replicate, open the Mobile XCode workspace (`Mobile.xcworkspace`) and then edit the scheme to use the Release build configuration ([step 2 on this page](https://reactnative.dev/docs/publishing-to-app-store)). Then attempt to build the app.

I also had to update relative paths for `node_modules` in `Podfile` and the `Bundle React Native code and images` phase in Build Phases in XCode.

**Comment by ceremonious** [comment]
I tried upgrading + adding the debug config line, but I was still running into the error + not seeing any debugging output. I even tried deleting the `metro.config.js` file completely and doing a build, and the error log looked exactly the same. It seems like the `metro.config.js` file is not being used when building from XCode.

I attached the error log I'm seeing in XCode when I try to do a release build [acmebuildlogs.txt](https://github.com/nrwl/nx-react-native/files/5640216/acmebuildlogs.txt).

**Comment by jaysoo** [comment]
If the config isn't being picked up then that would make sense. Need to check the shell scripts in the xcode project again, maybe I missed updating something there.

**Comment by jaysoo** [comment]
@ceremonious Can you also make sure you are on `10.4.8-beta.8`? You should be able to see some debug statements if you set `{ debug: true }` in the metro config.

**Comment by ceremonious** [comment]
I was on `10.4.8-beta.1`. I upgraded to `10.4.8-beta.7` (I don't see a beta.8 available) and it looks like it's working better now. It seems like when I run the release build from XCode, it's looking for `metro.config.js` in the base folder, instead of in the app folder.

I got the following error after I copied my `metro.config.js` file to my base folder:

```
[Nx] Failed to locate tsconfig}
error Unable to resolve module `@acme/ui-header` from `apps/mobile/App.tsx`: @acme/ui-header could not be found within the project.
```

I only see the following error if the `metro.config.js` file is not in my base folder:

```
error Unable to resolve module `@acme/ui-header` from `apps/mobile/App.tsx`: @acme/ui-header could not be found within the project.
```

I have a `tsconfig.base.json` file in my base folder, so now sure why it's unable to locate my tsconfig.

**Comment by ceremonious** [comment]
Update: I fixed the problem in our repo. The issue was that we didn't have symlinks created for `node_modules` in `apps/heartbeat-react-native`. I had never run `nx run-ios heartbeat-react-native` because I've been doing most of my testing on a local device instead of a simulator, so the symlink never got created by NX. Since there was no symlink, XCode was looking in the base folder instead of the app folder, so it was unable to find the `metro.config.js` and `tsconfig.json` files.

**Comment by jaysoo** [comment]
@ceremonious That's great! We will be providing migrations moving forward if any setup changes are needed.
