### ISSUE TITLE
Support for react-native-web

### ISSUE THREAD

**Issue by igamidanes** [nrwl/nx-react-native#25]
Would support for react-native-web be implemented or optional instructions?

**Comment by jaysoo** [comment]
@igamidanes What sort of support are you looking for? You can use `react-native-web` if you install it manually, but we don't  have any plans to provide code generation, etc. specifically for `react-native-web`.

For code generation, you can always write your own [workspace schematics](https://nx.dev/latest/react/guides/monorepo-nx-enterprise#workspace-schematics) to generate with `react-native-web`.

**Comment by farcaller** [comment]
It's not quite clear how to do the aliasing required for react-native-web to work. The mobile app will work fine with `import ... from 'react-native'`, but the react app will need to alias that import to the `'react-native-web'` instead. Some docs on how to do that would be really helpful.

**Comment by hanselabreu** [comment]
I believe this [article](https://blog.nrwl.io/introducing-react-native-support-for-nx-48d335e90c89) is what you're looking for

**Comment by farcaller** [comment]
That's it, thanks!
