### ISSUE TITLE
Allow use of expo rather than pure React Native

### ISSUE THREAD

**Issue by nordfjord** [nrwl/nx-react-native#4]
Hi nrwl team!

I'm excited to see progress being made on a react-native plugin.

I'm wondering about the possibility of using [expo](https://expo.io/) rather than plain old react-native. The same way there are plugins for Next.js and react for nx.

**Comment by goofiw** [comment]
I support going pure native, as it gives the most flexibility.  I'm looking forward to building some native modules in my workspace libs to keep all the code together

**Comment by nordfjord** [comment]
@goofiw I think you misunderstood me.
I'm not advocating for removing pure react-native support.
I'm advocating for adding expo support.

In much the same way that there's a react plugin (nrwl/react) and a next.js plugin (nrwl/next) for web.

For people who prefer a batteries included approach to native development expo is a fantastic choice.

**Comment by goofiw** [comment]
Maybe this is me not understanding the plugins ecosystem very well, but I would think the react and next plugins are separated for a reason.  Adding expo support may belong in its own, separate plugin.

**Comment by nordfjord** [comment]
@jaysoo Sounds reasonable. Thank you. My guess is much of the code would be shared.

I'll close this issue, since this isn't a priority.

**Comment by hanselabreu** [comment]
This would be nice 👍

**Comment by cgnuechtel** [comment]
There is a "Expo Managed Plugin for Nx":
https://github.com/JacopoPatroclo/nx-react-native-expo

It seems to work out of the box.

**Comment by violabg** [comment]
Are there any news on this?

**Comment by AlexJWayne** [comment]
I've been using that community plugin and been having [some issues](https://github.com/JacopoPatroclo/nx-react-native-expo/issues/21) I'm looking at co-opting the official react native plugin for this, but it's a bit tricky to figure out exactly how to modify the command and import an existing expo codebase.

Are there any docs or guides out there on how to get this all to work properly?
