### ISSUE TITLE
Command to regenerate native app node_modules

### ISSUE THREAD

**Issue by monroeinstitute** [nrwl/nx-react-native#41]
It seems that NX manages a second node modules folder inside the native app.  Is there a manual command to move those files there?  I'm trying to deploy via bitrise, and it isn't finding nx_post_install in the right place and so is failing when cocoapods runs.

**Comment by jaysoo** [comment]
@monroeinstitute Not at this moment, but you could write a scrip that calls this function.
```
const { ensureNodeModulesSymlink } = require('@nrwl/react-native/src/utils/ensure-node-modules-symlink');
ensureNodeModulesSymlink('/path/to/workspace', '/path/to/workspace/apps/myapp');
```

I think we should add a command `nx ensure-symlink myapp` to help with this.

**Comment by xiongemi** [comment]
the command `nx ensure-symlink myapp` has been added

**Comment by omairahmed63** [comment]
how to install react-navigation inside nx native app and update ios pods? I did the following and getting errors when I am updating pods: 
npm install @react-navigation/native
cd app/my-native/ios
npx pod-install or pod install 
error = [!] Invalid `Podfile` file: cannot load such file

PLEASE HELP
