### ISSUE TITLE
Build Faild

### ISSUE THREAD

**Issue by ckhandla94** [nrwl/nx-react-native#45]
- I have follow the steps of the document. I have not made any changes,  I am just trying to run project.
I am getting this error.
![image](https://user-images.githubusercontent.com/27082896/108588147-ad44b700-737d-11eb-8eb1-f60fd487afd3.png)

**Comment by jaysoo** [comment]
It should be working in the latest release. There was an error bundling JS due to incompatible versions of metro.

```
nx migrate @nrwl/workspace@latest @nrwl/react-native@latest
yarn
nx migrate --run-migrations=migrations.json
```

**Comment by ckhandla94** [comment]
@jaysoo  Thanks for reply, I have run the command but still I am getting build fail error.

![image](https://user-images.githubusercontent.com/27082896/109375783-5727c480-78e5-11eb-80ca-a1a26cd7bd7e.png)
