### ISSUE TITLE
Build no longer works for developing plugins

### ISSUE THREAD

**Issue by goofiw** [nrwl/nx-react-native#47]
Repro:
Node Version: tried 12 and 14
1a. watched video here: https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md
1.  fork nx-react-native
2. install deps with `yarn`
3. run `yarn test`
4. observe failure to build due to `names` import

(I tried fixing by importing the new names function from the devkit)[https://github.com/nrwl/nx-react-native/pull/46] and also by importing the reexported names function from `nrwl/workspace`, but then the tests run but the generator fails silently:

```
 FAIL  packages/react-native/src/schematics/application/application.spec.ts (5.723 s)
  ● app › should generate files

    expect(received).toBeTruthy()

    Received: false

      40 |   it('should generate files', async () => {
      41 |     const tree = await runSchematic('app', { name: 'myApp' }, appTree);
    > 42 |     expect(tree.exists('apps/my-app/App.tsx')).toBeTruthy();
         |                                                ^
      43 |     expect(tree.exists('apps/my-app/index.js')).toBeTruthy();
      44 | 
      45 |     const tsconfig = readJsonInTree(tree, 'apps/my-app/tsconfig.json');

      at src/schematics/application/application.spec.ts:42:48
      at fulfilled (../../node_modules/tslib/tslib.js:111:62)
  ```
  
  I did some poking around in the `nx` base repo, but it's unclear what is the current best way to update the generator.   The `node` and `react` plugins both do it a little differently.

**Comment by jaysoo** [comment]
This has been fixed on main branch now.
