### ISSUE TITLE
Generating a react-native library through the CLI adds unnecessary dependencies

### ISSUE THREAD

**Issue by hanselabreu** [nrwl/nx-react-native#49]
When generating a react-native library through the CLI, it ends up adding unnecessary dependencies. They appear to be the dependencies for `@nrwl/web` or `@nrwl/react` projects.

`dependencies`:
```
core-js
document-register-element
react-dom
```

`devDependencies`:
```
@nrwl/web
@testing-library/react
@types/react-dom 
```

Also, using the `--tags` does not create the tags.

Example command:

`nx generate @nrwl/react-native:lib test --directory=mobile/shared/components tags=scope:mobile,type:ui`

NX package versions:
```
// Project
"@nrwl/cli": "11.3.2",
"@nrwl/eslint-plugin-nx": "11.3.2",
"@nrwl/jest": "11.3.2",
"@nrwl/linter": "11.3.2",
"@nrwl/nest": "11.3.2",
"@nrwl/node": "11.3.2",
"@nrwl/react": "11.3.2",
"@nrwl/react-native": "^11.0.2",
"@nrwl/tao": "11.3.2",
"@nrwl/workspace": "11.3.2",

// Global
"nx": "11.3.2"
```

**Comment by xiongemi** [comment]
fixed in pr https://github.com/nrwl/nx-react-native/pull/68/files which is in release 12.3.6
