### ISSUE TITLE
Package unavailable

### ISSUE THREAD

**Issue by alveshelio** [nrwl/nx-react-native#5]
when trying to install the package with either npm i -D @nrwl/react-native or yarn add -D @nrwl/react-native I get

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nrwl%2freact-native - Not found

this: https://registry.npmjs.org/@nrwl/react-native returns an object `{ "error": "Not found" }`

**Comment by 0b3r** [comment]
It hasn't been released yet! See #1

**Comment by BassamHabash** [comment]
Hi @0b3r, @alveshelio 

How can add it to NX workspace? should I git clone the lib?
