### ISSUE TITLE
Migration to 11.4.1 broke .json imports

### ISSUE THREAD

**Issue by davisk4rpi** [nrwl/nx-react-native#54]
We recently ran `nx migrate @nrwl/react-native latest` 

One of the migrations added `metro-resolver: 0.59.0` to our dev dependencies. 

This library broke .json file imports in our translations library. 
```
Error: Unable to resolve module `./en/translation.json` from `libs/client/shared/translation/src/lib/translation.enum.ts`: ./en/translation.json could not be found within the project
```

The file exists and removing the dependency restores functionality.

**Comment by tocalvo** [comment]
Same here, upgrading and the .json imports fails.
Adding  
```
"resolutions": {
    "metro": "0.58.0"
  },

```  
temporarily to package.json works again (yarn)

**Comment by xiongemi** [comment]
i have tried with the latest nx-react-native version, which, is 12.3.6, it seems fine. I could do something like `import { name } from '../app.json';`.
