### ISSUE TITLE
package.json defaults to upper case name

### ISSUE THREAD

**Issue by wSedlacek** [nrwl/nx-react-native#58]
When creating a new project the `name` field in `package.json` is upper case.

```
{
  "name": "Bar",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "react-native": "*"
  }
}
```

I am rather new to React Native so I am not sure if this is a requirement by them but this does not follow the [NPM naming specification](https://docs.npmjs.com/creating-a-package-json-file/#:~:text=and%20version%20fields-,A%20package.,may%20contain%20hyphens%20and%20underscores.).
So I wanted to determine if this was intentional or if it could be changed.

**Comment by xiongemi** [comment]
it could be changed. submit a pr https://github.com/nrwl/nx-react-native/pull/65 to fix this.
