### ISSUE TITLE
The current build breaks the latest version of nx.

### ISSUE THREAD

**Issue by michaelypes** [nrwl/nx-react-native#62]
When installing an app it overrides the latest versions of @nrwl/linter with an older one which breaks nx commands. When will it be updated?

Linter version now is 12.2.0 and the version it overrides it with is 10.4.4 which has a breaking change as the index file is not in the route for 10.4.4.

Thanks

Michael

**Comment by xiongemi** [comment]
submit a pr https://github.com/nrwl/nx-react-native/pull/66/files to upgrade nx to 12.3.6, which is in release 12.3.6. it should work now with latest nx version.
