### ISSUE TITLE
Unable to resolve module generating using `generate @nrwl/react-native:lib <name>`

### ISSUE THREAD

**Issue by broerjuang** [nrwl/nx-react-native#72]
<img width="444" alt="Screen Shot 2021-06-14 at 17 32 19" src="https://user-images.githubusercontent.com/7804066/121878998-8d733d80-cd36-11eb-9c48-891912f27ec2.png">

I am trying to import module from libs but it cannot resolve.

First, I check workspace.json, tsconfig.base.json, and nx.json and I think it seems alright:

```json
    "paths": {
     ....
      "@dyna/ui/banner": ["libs/ui/banner/src/index.tsx"],
      "@dyna/example": ["libs/example/src/index.ts"]
    }

```

vscode can resolve the module but when I trigger the run-android, but the runtime is not knowing about this

**Comment by opula** [comment]
Running into the same issue.  Any resolution?

**Comment by xiongemi** [comment]
maybe kill the start command and run `nx start <your app name>` again, also reload the app in the device/simulator?

**Comment by opula** [comment]
@xiongemi Your solution works.  However, when I run "nx run-ios my-app" then it doesn't work.  Any ideas why this is the case?

**Comment by xiongemi** [comment]
> @xiongemi Your solution works. However, when I run "nx run-ios my-app" then it doesn't work. Any ideas why this is the case?

What error do you get? maybe keep the terminal with start command running? or maybe reload the app: in the terminal running the start command, enter 'r' to reload the app; or in the simulator, press mac 'Command' + 'd' to launch the debug menu and click "Reload".

**Comment by opula** [comment]
> What error do you get? maybe keep the terminal with start command running? or maybe reload the app: in the terminal running the start command, enter 'r' to reload the app; or in the simulator, press mac 'Command' + 'd' to launch the debug menu and click "Reload".

I've tried all of those.  Still get the same error.  For some reason it has access to the shared library directory when I run "nx start my-app" but not when I run "nx run-ios my-app".

![Simulator Screen Shot - iPhone 12 - 2021-06-14 at 21 15 19](https://user-images.githubusercontent.com/168711/121948439-8ad51000-cd57-11eb-8904-894624188d91.png)

**Comment by xiongemi** [comment]
I will take a look at this bug. for now, maybe just use the workaround to run `nx start ...` before `nx run-ios ...`.

**Comment by broerjuang** [comment]
Just asking the same solution to Slack channel. And I able to run the project on android. However, I haven't try to run on ios just yet.

The steps are:
1. create react-native lib under `libs/` or whatever your app layout
2. create a component using `@nrwl/react-native`

everything works fine. 

However, changing the paths inside `tsconfig.base.json` from `*.ts` to `*.tsx` will throw errors. since it tries to add `*.ts` extension again. For instance changing path to this  `/lib/some_package/src/index.tsx` will add additional `/lib/some_package/src/index.tsx.ts` so library will not resolved.

**Comment by broerjuang** [comment]
Awesome thanks @xiongemi for the answer!

**Comment by pipozoft** [comment]
I'm still experiencing this issue, even in a brand new project running the latest. If I import a component from another library it can not resolve the depency. The build command passes but the test doesnt. Please advice and th

**Comment by lorenamelor** [comment]
I have the same error here.
