### ISSUE TITLE
[Bugs] Having two or more RN apps in NX Workspace only trigger the first one

### ISSUE THREAD

**Issue by broerjuang** [nrwl/nx-react-native#78]
Hi, 

Thanks for the awesome plugin! I am having an issue when my workspace having more than one RN apps. Let's say, Apps A and B. and application A is created first. 

When I try to run the application B. It kept starting the Application A. I try to reset the cache but still not working. is it coming from this `ensureNodeModulesSymlink`? or any workaround to be able to change the project or running multiple apps on different terminal. Thanks

**Comment by xiongemi** [comment]
thanks for reporting. i will take a look.

**Comment by broerjuang** [comment]
I wish that I can help, will learn about how internals. Thanks @xiongemi for taking time.

**Comment by xiongemi** [comment]
@broerjuang I have tried to create 2 apps locally and it seems to work fine for me.
To run an app in ios simulator, i run `nx start app1` in 1 terminal ad run `nx run-ios app1` and it launches app1.
Then i run `nx start app2` and `nx run-ios app2` and it launches app2.
Do you have a GitHub repo i could take a look at?

**Comment by broerjuang** [comment]
Sorry the Github repo is private. I try to delete the apps and recreate it again. It seems alright. However one thing that differs when I re-create the new app is only display name. I will try it again (maybe tomorrow) and let you know if I can reproduce the issue.

**Comment by xiongemi** [comment]
ok. i don't think displayName would affect the build. usually for `ensureNodeModulesSymlink` error, maybe just need to delete node_modules folder under your app, not the one from the project root, and try to run on the app again. let me know if you still run into the same issue.

**Comment by broerjuang** [comment]
Will do and let you know. For now, I think that I am closing the issue since I can't reproduce. Sorry bothering you.
