### ISSUE TITLE
Unable to resolve module when import react:lib component

### ISSUE THREAD

**Issue by verycosy** [nrwl/nx-react-native#82]
I tried this [article](https://blog.nrwl.io/introducing-react-native-support-for-nx-48d335e90c89)s' instruction.
It works well when just create new react native app.
But when I generate react:lib for sharing components, error occurred.

```
error: Error: Unable to resolve module @multiplatform-todo/ui-heading from /Users/multiplatform-todo/apps/todo-app/src/app/App.tsx: @multiplatform-todo/ui-heading could not be found within the project or in these directories:
  apps/todo-app/node_modules
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | import * as React from 'react';
  2 | import { SafeAreaView, StyleSheet, View, Text } from 'react-native';
> 3 | import { UiHeading } from '@multiplatform-todo/ui-heading';
    |                            ^
  4 |
  5 | const App = () => {
  6 |   return (
    at ModuleResolver.resolveDependency (/Users/multiplatform-todo/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:234:15)
```
lib folder is successfully generated, but nx project can't resolve it.

**Comment by verycosy** [comment]
I think this issue is duplicated of https://github.com/nrwl/nx-react-native/issues/72

**Comment by wilzad** [comment]
I don't think this is an duplicate of the mentioned issue. I am facing the same issue. I have created a react library which works fine when imported into an react application. but i am not able to use the same inside a react native application. I would like to use the same library inside react web and react native. Is that possible ?
